data={'peak_hunts': [{'prepare': {'hypothesis': 'Adversaries may be using SSH to deploy a packet capture tool on FortiGate devices to intercept authentication traffic.', 'behavior_basis': 'SSH was used to deploy \
FortigateSniffer, which executes the diagnose sniffer packet command to monitor traffic for authentication \
protocols.', 'objective': 'Identify SSH sessions and process executions associated with deploying the sniffer \
command on FortiGate devices.', 'required_data_sources': ['SSH logs', 'Process creation events']}, 'execute': 
{'gather_data': ['Collect SSH session logs showing connections to FortiGate devices', "Capture process creation \
events for 'diagnose sniffer packet'"], 'analysis_steps': ['Correlate SSH login events with process creation of \
the sniffer command', 'Check for execution of the command with protocols like Kerberos/LDAP/SMB'], 
'supporting_evidence': ['SSH logs matching FortiGate IP addresses', "Process creation events for 'diagnose \
sniffer packet' with protocol parameters"]}, 'act': {'documentation_requirements': 'Record SSH session \
timestamps, FortiGate device identifiers, and command-line parameters used with the sniffer tool.', 
'findings_to_preserve': ['SSH connection patterns to FortiGate devices', 'Command-line arguments for the sniffer\
packet command'], 'future_hunt_recommendations': ['Monitor for SSH connections to network devices with unusual \
command executions', 'Track process creation events for diagnostic tools']}}, {'prepare': {'hypothesis': 
'Adversaries may be reconstructing captured network traffic into PCAP files to analyze cleartext credentials.', 
'behavior_basis': 'The SNIFTRAN component was used to process packet data into PCAP files as part of credential \
harvesting.', 'objective': 'Identify instances where SNIFTRAN is used to generate PCAP files from captured \
traffic.', 'required_data_sources': ['File creation/modification logs', 'Process execution logs']}, 'execute': 
{'gather_data': ['Collect file creation events for PCAP files', "Capture process executions involving \
'SNIFTRAN'"], 'analysis_steps': ['Check for file artifacts matching PCAP format generated by SNIFTRAN', 
'Correlate file creation with network traffic capture events'], 'supporting_evidence': ['PCAP files created with\
SNIFTRAN', 'Process execution logs showing SNIFTRAN processing packet data']}, 'act': 
{'documentation_requirements': 'Document file hashes, timestamps, and process execution contexts for PCAP \
files.', 'findings_to_preserve': ['PCAP file generation patterns', 'SNIFTRAN process execution timelines'], 
'future_hunt_recommendations': ['Monitor for file creation of PCAP files without clear legitimate sources', 
'Track process executions of unknown components handling network data']}}]}

peak_hunts = data["peak_hunts"]

md = ["# PEAK Hunt Hypotheses\n"]

for i, hunt in enumerate(peak_hunts, 1):
    md.extend([
        f"## Hunt {i}",
        "",
        "### Prepare",
        f"**Hypothesis:** {hunt['prepare']['hypothesis']}",
        "",
        f"**Behavior Basis:** {hunt['prepare']['behavior_basis']}",
        "",
        f"**Objective:** {hunt['prepare']['objective']}",
        "",
        "**Required Data Sources:**",
    ])

    for ds in hunt["prepare"]["required_data_sources"]:
        md.append(f"- {ds}")

    md.extend([
        "",
        "### Execute",
        "",
        "#### Gather Data",
    ])

    for item in hunt["execute"]["gather_data"]:
        md.append(f"- {item}")

    md.extend([
        "",
        "#### Analysis Steps",
    ])

    for item in hunt["execute"]["analysis_steps"]:
        md.append(f"- {item}")

    md.extend([
        "",
        "#### Supporting Evidence",
    ])

    for item in hunt["execute"]["supporting_evidence"]:
        md.append(f"- {item}")

    md.extend([
        "",
        "### Act",
        "",
        f"**Documentation Requirements:** {hunt['act']['documentation_requirements']}",
        "",
        "#### Findings to Preserve",
    ])

    for item in hunt["act"]["findings_to_preserve"]:
        md.append(f"- {item}")

    md.extend([
        "",
        "#### Future Hunt Recommendations",
    ])

    for item in hunt["act"]["future_hunt_recommendations"]:
        md.append(f"- {item}")

    md.extend(["", "---", ""])

markdown_content = "\n".join(md)

with open("peak_hunts.md", "w", encoding="utf-8") as f:
    f.write(markdown_content)

print("Saved peak_hunts.md")